version: "3"

services:
  nginx:
    image: nginx:1.17
    tmpfs:
      - /var/cache/nginx
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./www:/usr/share/nginx/html
      # ./cache:/var/cache/nginx/est-cache-php
    ports:
      - "3000:80"
      - "12321:12321"
      # "443:443"
    links:
      - php

  php:
    image: php:7.2-fpm
    volumes:
      - ./www:/usr/share/nginx/html
    # ports:
    #   - "9000:9000"
